# Generated by Django 3.2.25 on 2024-05-25 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_ponggame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='players',
            field=models.ManyToManyField(related_name='pong_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('fa', models.BooleanField(default=False)),
                ('game_process', models.BooleanField(default=False)),
                ('game_mode', models.CharField(max_length=25)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='game.ponggame')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('game_mode', models.CharField(max_length=25)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_histories', to='game.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='game.player')),
            ],
        ),
    ]
