# Generated by Django 3.2.25 on 2024-05-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20240525_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_players', to='game.ponggame'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_mode',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
