# Generated by Django 3.2.25 on 2024-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20240527_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
