# Generated by Django 3.2.25 on 2024-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='language',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
