# Generated by Django 3.2.25 on 2024-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2),
        ),
    ]
